name: Upload Website

on:
  push:
    branches:
    - deploy

jobs:
    upload:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2.3.2

        - name: Install and build
          uses: actions/setup-node@v1
          with:
            node-version: 16
        - run: npm install -g yarn

        - name: Print directory path
          run: echo "$GITHUB_WORKSPACE"

        - name: Install Dependencies
          run: yarn install

        - name: Print directory path
          run: echo "$GITHUB_WORKSPACE"

        - name: build
          run: yarn build

        - name: Set up AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1  # Replace with your desired AWS region
  
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Upload to S3
          run: aws s3 sync ./out s3://myportfolio-xc01/ --exclude ".git*"